### ISSUE TITLE
Use ArtifactHub Chart Annotations for capturing meta information

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/openmetadata-helm-charts#243]
Ref - https://artifacthub.io/docs/topics/annotations/helm/

Currently, we are interested in -

- [ ] `artifacthub.io/images`
- [ ] `artifacthub.io/license` (https://choosealicense.com/licenses/apache-2.0/)
- [ ] `artifacthub.io/prerelease`
- [ ] `artifacthub.io/recommendations` (For the dependencies of bitnami/mysql , airflow and opensearch
- [ ] `artifacthub.io/containsSecurityUpdates`
- [ ] `support` (Pointing to our github issues of Helm Chart) 
- [ ] `kubeVersion` (We support Kubernetes Version >=1.24)

**Comment by safayavatsal** [comment]
New PR with required changes - https://github.com/open-metadata/openmetadata-helm-charts/pull/281#issuecomment-2500005817
